// <auto-generated />
using E_Recrutement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Recrutement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250129114509_Initial-migration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Recrutement.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            Degree = "Master",
                            ExperienceYears = 5,
                            FirstName = "John",
                            LastName = "Doe",
                            Resume = "Resume_JohnDoe.pdf",
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            Degree = "Bachelor",
                            ExperienceYears = 3,
                            FirstName = "Jane",
                            LastName = "Smith",
                            Resume = "Resume_JaneSmith.pdf",
                            Title = "Data Analyst"
                        });
                });

            modelBuilder.Entity("E_Recrutement.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("recruiterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("recruiterId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractType = "CDI",
                            Position = "Backend Developer",
                            Profile = "Master",
                            Salary = 15000m,
                            Sector = "IT",
                            recruiterId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContractType = "CDD",
                            Position = "Financial Analyst",
                            Profile = "Bachelor",
                            Salary = 12000m,
                            Sector = "Finance",
                            recruiterId = 2
                        });
                });

            modelBuilder.Entity("E_Recrutement.Models.Recruiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recruiters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "recruiterA@example.com",
                            Name = "Recruiter A",
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Email = "recruiterB@example.com",
                            Name = "Recruiter B",
                            Phone = "987654321"
                        });
                });

            modelBuilder.Entity("E_Recrutement.Models.Offer", b =>
                {
                    b.HasOne("E_Recrutement.Models.Recruiter", "recruiter")
                        .WithMany()
                        .HasForeignKey("recruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recruiter");
                });
#pragma warning restore 612, 618
        }
    }
}
